version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "FerreteriaXYZ*"
      MSSQL_PID: Express
    volumes:
      - ./db/ferreteria-data:/var/opt/mssql
